<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');        
    }

    function index()
    {
        $id = $_GET['id'];
        $data['user'] = $this->User_model->get_user($id);
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
