<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tourdescription extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tourdescription_model');
    } 

    /*
     * Listing of tourdescription
     */
    function index()
    {
        $data['tourdescription'] = $this->Tourdescription_model->get_all_tourdescription();
        
        $data['_view'] = 'tourdescription/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tourdescription
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'Description' => $this->input->post('Description'),
				'Timeline' => $this->input->post('Timeline'),
				'Image' => $this->input->post('Image'),
				'IdTour' => $this->input->post('IdTour'),
				'Note' => $this->input->post('Note'),
            );
            
            $tourdescription_id = $this->Tourdescription_model->add_tourdescription($params);
            redirect('tourdescription/index');
        }
        else
        {            
            $data['_view'] = 'tourdescription/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tourdescription
     */
    function edit($IdDesciption)
    {   
        // check if the tourdescription exists before trying to edit it
        $data['tourdescription'] = $this->Tourdescription_model->get_tourdescription($IdDesciption);
        
        if(isset($data['tourdescription']['IdDesciption']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'Description' => $this->input->post('Description'),
					'Timeline' => $this->input->post('Timeline'),
					'Image' => $this->input->post('Image'),
					'IdTour' => $this->input->post('IdTour'),
					'Note' => $this->input->post('Note'),
                );

                $this->Tourdescription_model->update_tourdescription($IdDesciption,$params);            
                redirect('tourdescription/index');
            }
            else
            {
                $data['_view'] = 'tourdescription/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tourdescription you are trying to edit does not exist.');
    } 

    /*
     * Deleting tourdescription
     */
    function remove($IdDesciption)
    {
        $tourdescription = $this->Tourdescription_model->get_tourdescription($IdDesciption);

        // check if the tourdescription exists before trying to delete it
        if(isset($tourdescription['IdDesciption']))
        {
            $this->Tourdescription_model->delete_tourdescription($IdDesciption);
            redirect('tourdescription/index');
        }
        else
            show_error('The tourdescription you are trying to delete does not exist.');
    }
    
}
