<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tourdescription_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tourdescription by IdDesciption
     */
    function get_tourdescription($IdDesciption)
    {
        return $this->db->get_where('tourdescription',array('IdDesciption'=>$IdDesciption))->row_array();
    }
        
    /*
     * Get all tourdescription
     */
    function get_all_tourdescription()
    {
        $this->db->order_by('IdDesciption', 'asc');
        return $this->db->get('tourdescription')->result_array();
    }
        
    /*
     * function to add new tourdescription
     */
    function add_tourdescription($params)
    {
        $this->db->insert('tourdescription',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tourdescription
     */
    function update_tourdescription($IdDesciption,$params)
    {
        $this->db->where('IdDesciption',$IdDesciption);
        return $this->db->update('tourdescription',$params);
    }
    
    /*
     * function to delete tourdescription
     */
    function delete_tourdescription($IdDesciption)
    {
        return $this->db->delete('tourdescription',array('IdDesciption'=>$IdDesciption));
    }
}
